### ISSUE TITLE
cannot save images

### ISSUE THREAD

**Issue by kisonay** [studioespresso/craft3-unsplash#14]
All of a sudden, with the latest version of craft, I am receiving the following error:

2021-10-21 13:33:14 [-][1][bbr7f7kqm8udc4i5ejlr0rkf6m][warning][application] Prevented saving ...craft/storage/runtime/assets/tempuploads/unsplash/photo-719838374.jpg as an asset. It must be located within a temp directory or the project root (excluding system directories).

any ideas? it looks as though the temp uploads directory within within the project root.

the endpoint returns the following:

error: "array_map() expects parameter 1 to be a valid callback, function '_normalizeTempPath' not found or invalid function name"
exception: "yii\\base\\ErrorException"
file: "/Users/...craft/vendor/craftcms/cms/src/elements/Asset.php"
line: 2343

**Comment by janhenckens** [comment]
hey @kisonay, that's strange! Latest version of Craft being 3.7.17.2?

**Comment by janhenckens** [comment]
Ok, I'm able to reproduce and trace this back to this change on Craft's side https://github.com/craftcms/cms/commit/9d65a87eda6ad811410782e1a5a9d5aa1f5cf890.
The plugin was indeed using `getTempAssetUploadsPath()`to initially download the file from Unsplash, and that location is treated as a system directory it seems.

Changing it to `getTempPath()` seems to fix it so expect a fix later today :)

**Comment by kisonay** [comment]
I appreciate you debugging. looking forward to the update.

**Comment by janhenckens** [comment]
Fixed in saturday's update!
